[package]
name = "rust"
version = "0.1.0"
edition = "2021"


[lib]
name = "aoc"
path = "src/lib.rs"

[[bin]]
name = "day1"
path = "src/day_01.rs"

[[bin]]
name = "day3"
path = "src/day_03.rs"

[dependencies]
